substitutions:
  name: name
  friendly_name: My Friedly Name

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}

packages:
  package_import_url: github://LeonardoGandini/DivineNetwork/MultiSens-Core.yaml

logger:

api:
  encryption:
    key: ""

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  #
  #manual_ip:
  #  static_ip: 192.168.1.5
  #  gateway: 192.168.1.1
  #  subnet: 255.255.255.0
  #  dns1: 192.168.1.1
